import { createDancer } from './dance.js';
import { createPerformance } from './performance.js';
import { models, modelById, loadAsset, instantiateAsset } from './models.js';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import './style.css';

const $ = s => document.querySelector(s);
$('#app').innerHTML = `
<header><a class="brand" href="./"><b class="logo">H</b> HyperStage <span>STUDIO</span></a><div class="project-name">Untitled performance <span>本機專案</span></div><button id="save">↥ 儲存專案</button><button id="shot" class="primary">▣ 擷取畫面</button></header>
<main><aside class="library"><div class="section-heading"><h2>模型庫</h2><span class="count">12</span></div><p class="muted">YOUR CAST, YOUR STAGE</p><div class="model-list">${models.map(({id,name,format,preview},i)=>`<button class="model-card ${i===0?'selected':''}" data-model="${id}"><div class="model-preview" id="thumb${id}"><span>${String(id).padStart(2,'0')}</span>${preview?`<img src="${preview}" alt="${name} 預覽">`: `<b>${name}</b>`}</div><div class="model-info"><strong>${name}</strong><span>角色 ${id} · ${format}</span><i>${i===0?'●':'＋'}</i></div></button>`).join('')}</div><button id="import" class="upload">＋ 匯入 GLB／FBX 模型</button><input id="file" type="file" accept=".glb,.fbx" hidden><div class="library-note"><b>從模型，到你的舞台。</b><p>拖曳旋轉視角，滾輪縮放。<br>選擇角色，開始創作。</p></div><button id="load-project" class="subtle">↳ 開啟已儲存專案</button><input id="project-file" type="file" accept=".json" hidden></aside>
<section class="workspace"><div class="viewport-bar"><span><i class="live-dot"></i> 舞台預覽 <small>REALTIME 3D</small></span><div><button id="grid" class="tool active">▦ 網格</button><button id="reset-camera" class="tool">⌖ 重設視角</button></div></div><div id="viewport"><div class="stage-label">SCENE 01 <span>/</span> <b id="stage-name">紫夜舞台</b></div><div id="loading" role="status">載入角色中…</div><div class="view-presets"><button data-view="front">正面</button><button data-view="side">側面</button><button data-view="top">俯視</button></div><div class="viewport-footer"><span id="model-status">HYPER3D MODEL</span><span>拖曳旋轉 · 右鍵平移 · 滾輪縮放</span></div></div>
<section class="timeline"><div class="transport"><div><button id="rewind" title="回到起點">⏮</button><button id="play" class="play" aria-label="播放">▶</button><button id="loop" class="active" title="循環播放">↻</button><strong id="time">00:00.00</strong><span class="muted">/ 00:12.00</span></div><div><select id="speed" aria-label="播放速度"><option value="0.5">0.5×</option><option value="1" selected>1.0×</option><option value="1.5">1.5×</option><option value="2">2.0×</option></select><button id="add-key">◇ 新增關鍵影格</button></div></div><div class="track"><span class="track-name">◈ 角色變換</span><div class="track-body"><div class="ruler">${[0,2,4,6,8,10,12].map(n=>`<span>${String(n).padStart(2,'0')}s</span>`).join('')}</div><div class="clip"><span id="clip-name">靜態展示</span><div id="keys"></div></div><input id="scrub" aria-label="時間軸" type="range" min="0" max="12" value="0" step="0.01"></div></div><div class="timeline-bottom"><span>12 秒場景 · 30 FPS 影格刻度</span><button id="clear-keys" class="subtle">清除關鍵影格</button><span>SPACE 播放 / 暫停</span></div></section></section>
<aside class="inspector"><div class="section-heading"><h2>場景設定</h2><span>⚙</span></div><section><h3>動態 <span>MOTION</span></h3><div class="motion-grid"><button data-motion="still" class="selected">◈<span>靜態展示</span></button><button data-motion="sway">〰<span>節奏搖擺</span></button><button data-motion="turn">↻<span>環繞旋轉</span></button><button data-motion="dance">♫<span>骨架舞蹈</span></button><button data-motion="float">♧<span>輕盈浮動</span></button></div><p class="hint">預設動態作用於整個模型；內建動畫依時間軸播放。</p></section><section><h3>模型變換 <button id="reset-transform" class="subtle">重設</button></h3>${[['rotation','朝向','0','-180','180','1','°'],['height','高度','0','0','2','0.01',''],['scale','大小','1','0.4','1.8','0.01','×']].map(([id,name,v,min,max,step,unit])=>`<label class="range-label" for="${id}">${name}<output id="${id}-value">${v}${unit}</output></label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${v}">`).join('')}</section><section><h3>舞台 <span>ENVIRONMENT</span></h3><div class="swatches"><button data-theme="violet" class="selected" aria-label="紫夜舞台" style="--swatch:#7970ad"></button><button data-theme="blue" aria-label="深海舞台" style="--swatch:#4e88ad"></button><button data-theme="rose" aria-label="玫瑰舞台" style="--swatch:#ac657d"></button><button data-theme="light" aria-label="白色攝影棚" style="--swatch:#c5c6cd"></button></div><label class="range-label" for="light">燈光強度<output id="light-value">100%</output></label><input id="light" type="range" min="30" max="200" value="100"><label class="toggle-row">自動環繞鏡頭<input id="orbit" type="checkbox"></label></section><div class="info"><span>✧</span><div>創作從這裡開始<p>以關鍵影格記錄角色的位置、朝向與大小，再播放你的場景。</p></div></div></aside></main><footer><span><i class="live-dot"></i> <b id="status">正在準備舞台</b></span><span>HYPERSTAGE <span class="muted">/ MMD-STYLE MOTION STUDIO</span></span><span>WebGL · 本機處理</span></footer><div id="toast" role="status"></div>`;

const viewport = $('#viewport');
const renderer = new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFShadowMap; renderer.toneMapping=THREE.ACESFilmicToneMapping;
viewport.prepend(renderer.domElement);
const scene=new THREE.Scene(); scene.background=new THREE.Color('#1d1b29'); scene.fog=new THREE.Fog('#1d1b29',12,30);
const camera=new THREE.PerspectiveCamera(36,1,0.1,80); const controls=new OrbitControls(camera,renderer.domElement); controls.enableDamping=true; controls.minDistance=2; controls.maxDistance=15; controls.maxPolarAngle=Math.PI/2+0.06;
function resetCamera(){camera.position.set(0,2.4,7.8);controls.target.set(0,1.35,0);controls.update();} resetCamera();
scene.add(new THREE.HemisphereLight(0xcbd0ff,0x635472,2));
const keyLight=new THREE.DirectionalLight(0xfff1e8,3.5);keyLight.position.set(3,6,5);keyLight.castShadow=true;keyLight.shadow.mapSize.set(2048,2048);scene.add(keyLight);
const rim=new THREE.DirectionalLight(0xa995ff,3);rim.position.set(-4,3,-2);scene.add(rim);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:0x25222f,roughness:.9}));floor.rotation.x=-Math.PI/2;floor.position.y=-.08;floor.receiveShadow=true;scene.add(floor);
const stage=new THREE.Mesh(new THREE.CylinderGeometry(1.7,1.8,.12,96),new THREE.MeshStandardMaterial({color:0x363142,metalness:.35,roughness:.55}));stage.position.y=-.025;stage.receiveShadow=true;scene.add(stage);
const ring=new THREE.Mesh(new THREE.TorusGeometry(1.72,.012,8,128),new THREE.MeshBasicMaterial({color:0xb8a4ff}));ring.rotation.x=Math.PI/2;ring.position.y=.038;scene.add(ring);
const grid=new THREE.GridHelper(30,60,0x51495f,0x34313e);grid.position.y=-.07;scene.add(grid);
const actor=new THREE.Group();scene.add(actor);
let dancer=null;
let root=null,mixer=null,request=0,currentModel=1,time=0,playing=false,loop=true,motion='still',theme='violet',keys=[],base={rotation:0,height:0,scale:1},last=performance.now();
const cache=new Map();
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function dispose(obj){obj.traverse(n=>{n.geometry?.dispose(); for(const m of (Array.isArray(n.material)?n.material:[n.material]))if(m){for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();}});}
async function loadModel(source,id,format=modelById(id)?.format||'GLB'){const ticket=++request;$('#loading').hidden=false;$('#loading').textContent='載入角色中…';$('#status').textContent='載入模型中';try{const gltf=cache.get(source)||await loadAsset(source,format);if(ticket!==request){if(!cache.has(source))dispose(gltf.scene);return;}if(typeof id==='number')cache.set(source,gltf);if(root){actor.remove(root);if(currentModel==='custom')dispose(root);}root=instantiateAsset(gltf);dancer=createDancer(root);actor.add(root);currentModel=id;mixer=gltf.animations.length?new THREE.AnimationMixer(root):null;gltf.animations.forEach(c=>mixer.clipAction(c).play());$('#model-status').textContent=`${id==='custom'?'匯入角色':`角色 ${String(id).padStart(2,'0')}`} · ${format} · ${gltf.animations.some(c=>c.duration>.1)?'內建動畫':gltf.animations.length?'骨架姿勢':'靜態網格'}`;$('#status').textContent='舞台就緒';document.querySelectorAll('[data-model]').forEach(b=>{b.classList.toggle('selected',Number(b.dataset.model)===id);b.querySelector('i').textContent=Number(b.dataset.model)===id?'●':'＋';});$('#loading').hidden=true;if(typeof id==='number'&&!$('#thumb'+id+' img')){applyPose();renderer.render(scene,camera);const img=new Image();img.src=renderer.domElement.toDataURL('image/webp',.7);img.alt=`角色 ${String(id).padStart(2,'0')} 預覽`;$('#thumb'+id).append(img);}return true;}catch(e){if(ticket!==request)return false;$('#loading').textContent='模型載入失敗，請重新選擇或匯入 GLB／FBX';$('#status').textContent='載入失敗';console.error(e);return false;}}
function setMotion(value){dancer?.reset();motion=value;if(value==='dance'&&!dancer?.supported)toast('此模型沒有可用骨架，請選用 FBX 角色');document.querySelectorAll('[data-motion]').forEach(b=>b.classList.toggle('selected',b.dataset.motion===value));$('#clip-name').textContent=$(`[data-motion="${value}"] span`).textContent;}
function pose(){if(!keys.length)return base;const sorted=[...keys].sort((a,b)=>a.time-b.time);const a=[...sorted].reverse().find(k=>k.time<=time)||sorted[0],b=sorted.find(k=>k.time>=time)||sorted.at(-1);const p=a===b?0:(time-a.time)/(b.time-a.time);return Object.fromEntries(['rotation','height','scale'].map(k=>[k,THREE.MathUtils.lerp(a[k],b[k],p)]));}
function applyPose(){const p=pose(),t=time*Math.PI*2;actor.position.set(0,p.height,0);actor.rotation.set(0,THREE.MathUtils.degToRad(p.rotation),0);actor.scale.setScalar(p.scale);if(motion==='sway'){actor.rotation.z=Math.sin(t/2)*.09;actor.position.x=Math.sin(t/2)*.17;}if(motion==='turn')actor.rotation.y+=t/12;if(motion==='float')actor.position.y+=(1-Math.cos(t/3))*.16;if(motion==='dance'&&dancer?.supported)dancer.apply(time,{intensity:.85});else if(mixer)mixer.setTime(time);}
function setPlaying(value){playing=value;$('#play').textContent=value?'Ⅱ':'▶';$('#play').setAttribute('aria-label',value?'暫停':'播放');}
function updateTime(){ $('#scrub').value=time;$('#time').textContent=`00:${time.toFixed(2).padStart(5,'0')}`;$('#scrub').style.setProperty('--progress',`${time/12*100}%`);}
function renderKeys(){$('#keys').innerHTML=keys.map(k=>`<span style="left:${k.time/12*100}%" title="${k.time.toFixed(2)} 秒">◆</span>`).join('');}
function updateInputs(){for(const k of ['rotation','height','scale']){$('#'+k).value=base[k];$('#'+k+'-value').textContent=Number(base[k]).toFixed(k==='rotation'?0:2)+(k==='rotation'?'°':k==='scale'?'×':'');}}
const palettes={violet:['#1d1b29',0x25222f,0xb8a4ff,'紫夜舞台'],blue:['#142331',0x1d2c3b,0x7bd3ff,'深海舞台'],rose:['#2d1c29',0x382333,0xffa1c5,'玫瑰舞台'],light:['#bbbbc6',0x9696a2,0xffffff,'白色攝影棚']};
function setTheme(value){theme=value;const p=palettes[value];scene.background.set(p[0]);scene.fog.color.set(p[0]);floor.material.color.set(p[1]);ring.material.color.set(p[2]);$('#stage-name').textContent=p[3];document.querySelectorAll('[data-theme]').forEach(b=>b.classList.toggle('selected',b.dataset.theme===value));}
new ResizeObserver(()=>{const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}).observe(viewport);
renderer.setAnimationLoop(()=>{const now=performance.now(),dt=Math.min((now-last)/1000,.1);last=now;if(playing){time+=dt*Number($('#speed').value);if(time>=12){time=loop?time%12:12;if(!loop)setPlaying(false);}updateTime();}applyPose();if(!performanceShow.active)controls.autoRotate=$('#orbit').checked;controls.update();performanceShow.update(dt);renderer.render(scene,camera);});
document.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>loadModel(modelById(Number(b.dataset.model)).url,Number(b.dataset.model)));
document.querySelectorAll('[data-motion]').forEach(b=>b.onclick=()=>setMotion(b.dataset.motion));
document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));
$('#play').onclick=()=>{if(time>=12)time=0;setPlaying(!playing);};$('#rewind').onclick=()=>{time=0;setPlaying(false);updateTime();};$('#loop').onclick=()=>{loop=!loop;$('#loop').classList.toggle('active',loop);};$('#scrub').oninput=e=>{time=Number(e.target.value);updateTime();};
window.addEventListener('keydown',e=>{if(!performanceShow.active&&e.code==='Space'&&!['INPUT','SELECT','BUTTON'].includes(document.activeElement.tagName)){e.preventDefault();$('#play').click();}});
for(const k of ['rotation','height','scale'])$('#'+k).oninput=e=>{base={...pose(),[k]:Number(e.target.value)};if(keys.length){const index=keys.findIndex(x=>Math.abs(x.time-time)<.02);const frame={time,...base};if(index<0)keys.push(frame);else keys[index]=frame;renderKeys();}updateInputs();};
$('#reset-transform').onclick=()=>{base={rotation:0,height:0,scale:1};keys=[];renderKeys();updateInputs();};
$('#add-key').onclick=()=>{const frame={time,...pose()};keys=keys.filter(k=>Math.abs(k.time-time)>.02);keys.push(frame);renderKeys();toast(`已記錄 ${time.toFixed(2)} 秒的關鍵影格`);};$('#clear-keys').onclick=()=>{base={...pose()};keys=[];renderKeys();updateInputs();};
$('#light').oninput=e=>{keyLight.intensity=3.5*e.target.value/100;$('#light-value').textContent=e.target.value+'%';};$('#grid').onclick=()=>{grid.visible=!grid.visible;$('#grid').classList.toggle('active',grid.visible);};$('#reset-camera').onclick=resetCamera;
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{controls.target.set(0,1.35,0);const v=b.dataset.view;camera.position.set(...(v==='front'?[0,1.5,8]:v==='side'?[8,1.5,0]:[0,8,.01]));controls.update();});
function download(data,name){const a=document.createElement('a');a.href=data;a.download=name;a.click();}
$('#shot').onclick=()=>{renderer.render(scene,camera);download(renderer.domElement.toDataURL('image/png'),'hyperstage-scene.png');toast('舞台截圖已匯出');};
$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;const url=URL.createObjectURL(f);await loadModel(url,'custom',f.name.toLowerCase().endsWith('.fbx')?'FBX':'GLB');URL.revokeObjectURL(url);e.target.value='';};
$('#save').onclick=()=>{if(currentModel==='custom'){toast('匯入模型請先切換回內建角色，再儲存專案');return;}const data={version:1,model:currentModel,base,motion,theme,keys,time,light:Number($('#light').value),speed:Number($('#speed').value),loop,grid:grid.visible,orbit:$('#orbit').checked,camera:camera.position.toArray(),target:controls.target.toArray()};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));download(url,'hyperstage-project.json');setTimeout(()=>URL.revokeObjectURL(url),1000);toast('專案已儲存');};
$('#load-project').onclick=()=>$('#project-file').click();$('#project-file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const p=JSON.parse(await f.text());const finite=(n,a,b)=>Number.isFinite(n)&&n>=a&&n<=b;const validPose=x=>x&&finite(x.rotation,-180,180)&&finite(x.height,0,2)&&finite(x.scale,.4,1.8);const vec=x=>Array.isArray(x)&&x.length===3&&x.every(n=>finite(n,-100,100));if(p.version!==1||!modelById(p.model)||!['still','sway','turn','float','dance'].includes(p.motion)||!Object.hasOwn(palettes,p.theme)||!validPose(p.base)||!Array.isArray(p.keys)||p.keys.length>1000||!p.keys.every(k=>validPose(k)&&finite(k.time,0,12))||!finite(p.time,0,12)||!finite(p.light,30,200)||![.5,1,1.5,2].includes(p.speed)||!vec(p.camera)||!vec(p.target))throw Error('格式錯誤');if(!await loadModel(modelById(p.model).url,p.model))return;base=p.base;keys=p.keys;time=p.time;setMotion(p.motion);setTheme(p.theme);$('#light').value=p.light;$('#light').oninput({target:$('#light')});$('#speed').value=p.speed;loop=!!p.loop;$('#loop').classList.toggle('active',loop);grid.visible=!!p.grid;$('#grid').classList.toggle('active',grid.visible);$('#orbit').checked=!!p.orbit;camera.position.fromArray(p.camera);controls.target.fromArray(p.target);controls.update();setPlaying(false);updateTime();updateInputs();renderKeys();toast('專案已開啟');}catch{toast('無法開啟：請選擇有效的 HyperStage 專案 JSON');}finally{e.target.value='';}};
loadModel('/models/1/base_basic_pbr.glb',1);

let themeBeforeShow=theme;
const performanceShow=createPerformance({scene,camera,controls,actor,stage,ring,setTheme,toast,onEnter:()=>{themeBeforeShow=theme;setPlaying(false);},onExit:()=>setTheme(themeBeforeShow)});
performanceShow.enter();
